name: Auto Merge and Version Tag

on:
  workflow_call:

jobs:
  merge_and_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Merge to v.1.x
        run: |
          git checkout v.1.x
          git merge main
          git push origin v.1.x

      - name: Get Latest Commit Version
        id: get_latest_version
        run: echo "::set-output name=version::$(git describe --abbrev=0 --tags)"

      - name: Create Version Tag
        run: |
          version=${{ steps.get_latest_version.outputs.version }}
          git tag -a $version -m "Version $version"
          git push origin $version
