name: Licensed

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # prefer to use a full fetch for licensed workflows
      # https://github.com/jonabc/setup-licensed/releases/tag/v1.1.1
      - uses: jonabc/setup-licensed@d6b3a6f7058c2b40c06d205e13e15c2418977566
        with:
          version: '3.x'
      - run: npm ci
      - run: licensed status