name: Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Execute tests
        run: vendor/bin/phpunit

      - name: Report Results
        if: failure()
        run: |
          echo "::set-output name=status::failed"
          echo "::set-output name=comment::Tests failed in PHP ${{ matrix.php }}."

      - name: Mark as Skipped
        if: success()
        run: |
          echo "::set-output name=status::skipped"
          echo "::set-output name=comment::Tests skipped in PHP ${{ matrix.php }}."

  comment:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check Test Status
        id: check_test_status
        run: echo "Test status is ${{ needs.tests.outputs.status }}"

      - name: Create Comment
        if: steps.check_test_status.outputs.status == 'failed' || steps.check_test_status.outputs.status == 'skipped'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = "${{ steps.check_test_status.outputs.comment }}";
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });